/**
 * The app's icon set: ReUI Motion Icons, outline style only. Import from here
 * so a swap of style or vendor is one file. Every icon takes `className`;
 * size with `size-4` etc.
 */
export { default as CopyIcon } from '@/reui/icons/animated/outline/copy'
export { default as CopySuccessIcon } from '@/reui/icons/animated/outline/copy-success'
export { default as CheckIcon } from '@/reui/icons/animated/outline/check'
export { default as RefreshIcon } from '@/reui/icons/animated/outline/refresh-arrow-clockwise'
export { default as BookIcon } from '@/reui/icons/animated/outline/book'
export { default as SettingsIcon } from '@/reui/icons/animated/outline/setting-2'
export { default as CloudIcon } from '@/reui/icons/animated/outline/cloud'
export { default as RouteIcon } from '@/reui/icons/animated/outline/route'
export { default as TrashIcon } from '@/reui/icons/animated/outline/trash'
export { default as StarIcon } from '@/reui/icons/animated/outline/star'
export { default as SearchIcon } from '@/reui/icons/animated/outline/magnifier'
export { default as PlusIcon } from '@/reui/icons/animated/outline/plus'
export { default as PencilIcon } from '@/reui/icons/animated/outline/pencil'
export { default as DragIcon } from '@/reui/icons/animated/outline/drag'
export { default as EyeIcon } from '@/reui/icons/animated/outline/eye'
export { default as CloseIcon } from '@/reui/icons/animated/outline/cross'
export { default as DocumentIcon } from '@/reui/icons/animated/outline/document'
export { default as KeyboardIcon } from '@/reui/icons/animated/outline/keyboard'
export { default as ThemeIcon } from '@/reui/icons/animated/outline/night-day'
export { default as ClipboardIcon } from '@/reui/icons/animated/outline/clipboard'
export { default as MenuIcon } from '@/reui/icons/animated/outline/menu'
export { default as LayersIcon } from '@/reui/icons/animated/outline/row-vertical'
export { default as HistoryIcon } from '@/reui/icons/animated/outline/circle-arrow-anticlockwise-clock'
export { default as ImportIcon } from '@/reui/icons/animated/outline/add-files'
export { default as DownloadIcon } from '@/reui/icons/animated/outline/cloud-download'
export { default as UploadIcon } from '@/reui/icons/animated/outline/cloud-upload'
export { default as WebIcon } from '@/reui/icons/animated/outline/screen'
export { default as CliIcon } from '@/reui/icons/animated/outline/message-programming'
export { default as DeskIcon } from '@/reui/icons/animated/outline/laptop'
export { default as MobileIcon } from '@/reui/icons/animated/outline/phone'
export { default as OtherIcon } from '@/reui/icons/animated/outline/cube-3'
export { default as ExpandIcon } from '@/reui/icons/animated/outline/chevrons-down'
export { default as LockIcon } from '@/reui/icons/animated/outline/lock'
export { default as CommandIcon } from '@/reui/icons/animated/outline/command'
export { default as DataIcon } from '@/reui/icons/animated/outline/data'
export { default as ServerIcon } from '@/reui/icons/animated/outline/data'
export { default as GithubIcon } from '@/reui/icons/animated/outline/github'
export { default as SunIcon } from '@/reui/icons/animated/outline/sun'
export { default as MoonIcon } from '@/reui/icons/animated/outline/moon'
export { default as SnapshotIcon } from '@/reui/icons/animated/outline/scan-barcode'
export { default as CompareIcon } from '@/reui/icons/animated/outline/right-left'
export { default as FolderIcon } from '@/reui/icons/animated/outline/book-open'
export { default as BlocksIcon } from '@/reui/icons/animated/outline/elements'
export { default as InfoIcon } from '@/reui/icons/animated/outline/information'
export { default as DuplicateIcon } from '@/reui/icons/animated/outline/plus-circle'
export { default as CodeIcon } from '@/reui/icons/animated/outline/code'
